[font]
normal = {family = "FiraCode Nerd Font", style = "Regular"}
size = 11.0

[window]
padding = { x = 2, y = 2 }
dimensions = { columns = 90, lines = 25 }

opacity = 0.9
# blur = true

# decorations= "None"       # Disable window decoration

[scrolling]
history = 10000     # Default = 10000
multiplier = 5      # Defualt = 3

[cursor]
# style = { <shape>, <blinking> }
# shape = "Block" | "Underline" | "Beam"
# blinking = "Never" | "Off" | "On" | "Always"
style = { shape = "Beam", blinking = "On"}

# thickness = 0.5
blink_interval = 500        # Blink intervall in ms

unfocused_hollow = false

[mouse]
hide_when_typing = true


[colors]
# Dracula theme colors
primary = { foreground = "0xf8f8f2", background = "0x21222c" }

[colors.normal]
black = "0x21222c"
red = "0xff5555"
green = "0x50fa7b"
yellow = "0xf1fa8c"
blue = "0xbd93f9"
magenta = "0xff79c6"
cyan = "0x8be9fd"
white = "0xf8f8f2"

[colors.bright]
black = "0x6272a4"
red = "0xff6e6e"
green = "0x69ff94"
yellow = "0xffffa5"
blue = "0xd6acff"
magenta = "0xff92df"
cyan = "0xa4ffff"
white = "0xffffff"

[colors.search]
matches = { foreground = "0x000000", background = "0xffd700" }
focused_match = { foreground = "0x000000", background = "0x00ff00" }

[colors.line_indicator]
foreground = "0xff5555"
background = "0xff0000"

[colors.selection]
text = "CellForeground"
background = "#717782"
