# Manager configuration
[mgr]
prepend_keymap = [
    # Relative motions
    { on = ["1"], run = "plugin relative-motions 1", desc = "Move in relative steps" },
    { on = ["2"], run = "plugin relative-motions 2", desc = "Move in relative steps" },
    { on = ["3"], run = "plugin relative-motions 3", desc = "Move in relative steps" },
    { on = ["4"], run = "plugin relative-motions 4", desc = "Move in relative steps" },
    { on = ["5"], run = "plugin relative-motions 5", desc = "Move in relative steps" },
    { on = ["6"], run = "plugin relative-motions 6", desc = "Move in relative steps" },
    { on = ["7"], run = "plugin relative-motions 7", desc = "Move in relative steps" },
    { on = ["8"], run = "plugin relative-motions 8", desc = "Move in relative steps" },
    { on = ["9"], run = "plugin relative-motions 9", desc = "Move in relative steps" },

    # Compress files
    { on = ["C", "z"], run = "plugin ouch zip", desc = "Compress  zip" },
    { on = ["C", "t"], run = "plugin ouch tar", desc = "Compress  tar" },

    # Lazygit
    { on = ["L"], run = "plugin lazygit", desc = "Run LazyGit" },

    # Toggle preview
    { on = ["T"], run = "plugin toggle-pane min-preview", desc = "Toggle Preview" },

    # Restore deleted files
    { on = "u", run = "plugin restore", desc = "Restore last deleted files/folders" },

    # Disks
    { on  = "M", run = "plugin mount" },

    # Flash
    {on   = [ "s" ], run = "plugin searchjump", desc = "searchjump mode"},

    # Marks
    { on = [ "m" ], run = "plugin bookmarks save", desc = "Save current position as a bookmark" },
    { on = [ "'" ], run = "plugin bookmarks jump", desc = "Jump to a bookmark" },
    { on = [ "b", "d" ], run = "plugin bookmarks delete", desc = "Delete a bookmark" },
    { on = [ "b", "D" ], run = "plugin bookmarks delete_all", desc = "Delete all bookmarks" },

	# Linemode
	{ on = [ "F", "s" ], run = "linemode size",        desc = "Linemode: size" },
	{ on = [ "F", "p" ], run = "linemode permissions", desc = "Linemode: permissions" },
	{ on = [ "F", "b" ], run = "linemode btime",       desc = "Linemode: btime" },
	{ on = [ "F", "m" ], run = "linemode mtime",       desc = "Linemode: mtime" },
	{ on = [ "F", "o" ], run = "linemode owner",       desc = "Linemode: owner" },
	{ on = [ "F", "n" ], run = "linemode none",        desc = "Linemode: none" },
	{ on = [ "F", "r" ], run = "linemode rtime", desc = "Linemode: rtime" },

	# Tabs
	{ on = [ "g", "1", ], run = "tab_switch 0", desc = "Switch to tab 1" },
	{ on = [ "g", "2", ], run = "tab_switch 1", desc = "Switch to tab 2" },
	{ on = [ "g", "3", ], run = "tab_switch 2", desc = "Switch to tab 3" },
	{ on = [ "g", "4", ], run = "tab_switch 3", desc = "Switch to tab 4" },
	{ on = [ "g", "5", ], run = "tab_switch 4", desc = "Switch to tab 5" },
	{ on = [ "g", "6", ], run = "tab_switch 5", desc = "Switch to tab 6" },
	{ on = [ "g", "7", ], run = "tab_switch 6", desc = "Switch to tab 7" },
	{ on = [ "g", "8", ], run = "tab_switch 7", desc = "Switch to tab 8" },
	{ on = [ "g", "9", ], run = "tab_switch 8", desc = "Switch to tab 9" },

	{ on = "<C-p>", run = "tab_switch 1 --relative",  desc = "Switch to next tab" },
	{ on = "<C-n>", run = "tab_switch -1 --relative", desc = "Switch to previous tab" },
]


