[flavor]
# dark = "kanagawa"
# light = kanagawa missing
# dark = rose-pine missing
# light = rose-pine missing
dark = "catppuccin-mocha"
light = "catppuccin-latte"

[manager]
preview_hovered = { reversed = true }
