use_nerdfont = true
flip_status_indicators = true
volnorm = true
library_tabs = ["tracks", "playlists", "artists", "browse"]

[theme]
title = "light green"
playing = "light green"
statusbar_progress = "light green"
statusbar = "light blue"
highlight_bg = "blue"
highlight = "light black"
