notARepository: "skip"
disableStartupPopups: true
promptToReturnFromSubprocess: false
showCommandLog: false

os:
  editPreset: "nvim"

git:
  paging:
    colorArg: always
    pager: delta --paging=never --detect-dark-light always --side-by-side

gui:
  nerdFontsVersion: "3"
  statusPanelView: allBranchesLog

  theme:
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - gray
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - black
    cherryPickedCommitBgColor:
      - darkgray
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
    defaultFgColor:
      - default
    searchingActiveBorderColor:
      - yellow

keybinding:
  universal:
    prevPage: <c-b>
    nextPage: <c-f>
