-- ╭──────────────────────────────────────────────────────────╮
-- │ Disable cutting                                          │
-- ╰──────────────────────────────────────────────────────────╯
-- The following options disables the ability to cut the
-- deleted text. So, if you yank a text, delete a text somewhere
-- else and want to paste the yanked text, it doesn't get
-- overwritten by the deleted (cutted) text.
--
-- Of course you can (and should) use the :register instead of
-- this "workaround", but for some people this method will be
-- more comfortable
--
-- DISCLAIMER: This file might not include every possible
--              delete command, so you might run into a case
--              where it won't delete but cut
--              (or just update this file with the missing shortcut)

local keymap = vim.keymap

-- Normal mode delete
keymap.set("n", "x", '"_x')
-- keymap.set("n", "D", '"_D')
-- keymap.set("n", "dd", '"_dd')
-- keymap.set("n", "dw", '"_dw')
-- keymap.set("n", "d$", '"_d$')
-- keymap.set("n", "d^", '"_d^')
-- keymap.set("n", "db", '"_db')
-- keymap.set("n", "diw", '"_diw')
-- keymap.set("n", "daw", '"_daw')
-- keymap.set("n", 'di"', '"_di"')
-- keymap.set("n", 'da"', '"_da"')
-- keymap.set("n", "di'", "\"_di'")
-- keymap.set("n", "da'", "\"_da'")
-- keymap.set("n", "di(", '"_di(')
-- keymap.set("n", "da(", '"_da(')
-- keymap.set("n", "di)", '"_di)')
-- keymap.set("n", "da)", '"_da)')
-- keymap.set("n", "di}", '"_di}')
-- keymap.set("n", "d%", '"_d%')
-- keymap.set("n", 'dt"', '"_dt"')
-- keymap.set("n", 'dT"', '"_dT"')
-- keymap.set("n", "dl", '"_dl')
-- keymap.set("n", "dh", '"_dh')
-- keymap.set("n", "df", '"_df')
-- keymap.set("n", "dF", '"_dF')
-- keymap.set("n", "dt", '"_dt')
-- keymap.set("n", "dk", '"_dk')
-- keymap.set("n", "dj", '"_dj')
--
-- -- Visual mode delete
-- keymap.set("v", "d", '"_d')
-- keymap.set("v", "x", '"_x')
-- keymap.set("v", "dl", '"_dl')
-- keymap.set("v", "dh", '"_dh')
-- keymap.set("v", "dk", '"_dk')
-- keymap.set("v", "dj", '"_dj')
-- keymap.set("v", "df", '"_df')
-- keymap.set("v", "dF", '"_dF')
-- keymap.set("v", "dt", '"_dt')
-- keymap.set("v", "dT", '"_dT')
--
-- -- Visual line mode
-- keymap.set("x", "d", '"_d')
-- keymap.set("x", "x", '"_x')
-- keymap.set("x", "dl", '"_dl')
-- keymap.set("x", "dh", '"_dh')
-- keymap.set("v", "dk", '"_dk')
-- keymap.set("v", "dj", '"_dj')
-- keymap.set("x", "df", '"_df')
-- keymap.set("x", "dF", '"_dF')
-- keymap.set("x", "dt", '"_dt')
-- keymap.set("x", "dT", '"_dT')
--
-- -- Visual block delete
-- keymap.set("s", "d", '"_d')
-- keymap.set("s", "x", '"_x')
-- keymap.set("s", "dl", '"_dl')
-- keymap.set("s", "dh", '"_dh')
-- keymap.set("s", "dk", '"_dk')
-- keymap.set("s", "dj", '"_dj')
-- keymap.set("s", "df", '"_df')
-- keymap.set("s", "dF", '"_dF')
-- keymap.set("s", "dt", '"_dt')
-- keymap.set("s", "dT", '"_dT')
